# Generated by Django 6.0.4 on 2026-04-19 20:39

from django.db import migrations


def seed_roles_and_access_rules(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    BusinessElement = apps.get_model('users', 'BusinessElement')
    AccessRoleRule = apps.get_model('users', 'AccessRoleRule')

    Role.objects.get_or_create(code='admin', defaults={'name': 'Администратор'})
    Role.objects.get_or_create(code='guest', defaults={'name': 'Гость'})
    book_el, _ = BusinessElement.objects.get_or_create(
        code='book',
        defaults={'name': 'Книги'},
    )
    AccessRoleRule.objects.update_or_create(
        role_id='guest',
        element=book_el,
        defaults={'read_permission': True, 'read_all_permission': False},
    )


def unseed_roles_and_access_rules(apps, schema_editor):
    BusinessElement = apps.get_model('users', 'BusinessElement')
    AccessRoleRule = apps.get_model('users', 'AccessRoleRule')

    AccessRoleRule.objects.filter(role_id='guest', element__code='book').delete()
    BusinessElement.objects.filter(code='book').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_access_rules, unseed_roles_and_access_rules),
    ]
